version: '3'

services:

  web:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/src/app
      - gem_cache:/gems
    environment:
      DATABASE_HOST: database
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: some-long-secure-password
      POSTGRES_DB: get-help-with-tech_development

  webpack_dev_server:
    build: .
    command: ./bin/webpack-dev-server
    ports:
      - "3035:3035"
    volumes:
      - .:/usr/src/app
      - gem_cache:/gems
    environment:
      - WEBPACKER_DEV_SERVER_HOST=0.0.0.0

  redis:
    image: redis

  database:
    image: postgres
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: some-long-secure-password
      POSTGRES_DB: get-help-with-tech_development

volumes:
  db_data:
  gem_cache:
