:concurrency: 2
:logfile: ./log/sidekiq.log
:queues:
  - default
  - mailers
  - scheduler
:schedule:
  UpdateRemainingDevicesJob:
    cron: '55 23 * * * Europe/London'  # every day at 11:55pm
    queue: scheduler
    description: Store daily total for remaining devices
  StageGiasDataJob:
    cron: '15 5 * * * Europe/London'  # every day at 5:15am
    queue: scheduler
    description: Stage GIAS school data
  StageTrustDataJob:
    cron: '30 5 * * * Europe/London' # every day at 5:30am
    queue: scheduler
    description: Stage GIAS trust data
  ApplyStagedAttributeChangesToTrustsJob:
    cron: '0 6 * * * Europe/London' # every day at 6:00am
    queue: scheduler
    description: Apply staged attribute changes to trusts
  NotifyMnosJob:
    cron: '0 8 * * 1-5 Europe/London'  # every weekday at 8:00am
    queue: scheduler
    description: Notify MNOs of requests
  DeleteOldSessionsJob:
    cron: '0 * * * * Europe/London' # on the hour, every hour
    queue: scheduler
    description: Delete old sessions
