# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)

MobileNetwork.upsert_all([
  { brand: '1pMobile', host_network: 'EE', participating_in_scheme: false, created_at: Time.now, updated_at: Time.now },
  { brand: '360Coms Telecom', host_network: 'Three', participating_in_scheme: false, created_at: Time.now, updated_at: Time.now },
  { brand: '365 Mobile', host_network: 'O2, Vodafone', participating_in_scheme: false, created_at: Time.now, updated_at: Time.now },
  { brand: 'AfriMobile', host_network: 'Three', participating_in_scheme: false, created_at: Time.now, updated_at: Time.now },
  { brand: 'Anywhere Care Ownfone (formerly Age UK Ownfone)', host_network: 'Vodafone', participating_in_scheme: false, created_at: Time.now, updated_at: Time.now },
  { brand: 'AlwaysOnline Wireless', host_network: 'Three', participating_in_scheme: false, created_at: Time.now, updated_at: Time.now },
  { brand: 'Anywhere Sim', host_network: 'O2, Vodafone, EE, Three', participating_in_scheme: false, created_at: Time.now, updated_at: Time.now },
  { brand: 'Asda Mobile', host_network: 'EE', participating_in_scheme: false, created_at: Time.now, updated_at: Time.now },
  { brand: 'Auracall Travel Talk', host_network: 'EE', participating_in_scheme: false, created_at: Time.now, updated_at: Time.now },
  { brand: 'Axis Telecom', host_network: 'EE', participating_in_scheme: false, created_at: Time.now, updated_at: Time.now },
  { brand: 'BT Mobile', host_network: 'EE', participating_in_scheme: false, created_at: Time.now, updated_at: Time.now },
  { brand: 'BT Onephone (BTOP)', host_network: 'EE', participating_in_scheme: false, created_at: Time.now, updated_at: Time.now },
  { brand: 'C4C Mobile', host_network: 'EE', participating_in_scheme: false, created_at: Time.now, updated_at: Time.now },
  { brand: 'Call & Give', host_network: 'EE', participating_in_scheme: false, created_at: Time.now, updated_at: Time.now },
  { brand: 'Calteq', host_network: 'EE', participating_in_scheme: false, created_at: Time.now, updated_at: Time.now },
  { brand: 'Champions Mobile', host_network: 'O2', participating_in_scheme: false, created_at: Time.now, updated_at: Time.now },
  { brand: 'CUniq', host_network: 'O2', participating_in_scheme: false, created_at: Time.now, updated_at: Time.now },
  { brand: 'CMLink', host_network: 'EE', participating_in_scheme: false, created_at: Time.now, updated_at: Time.now },
  { brand: 'CTExcel', host_network: 'EE', participating_in_scheme: false, created_at: Time.now, updated_at: Time.now },
  { brand: 'Ctrl Mobile', host_network: 'Three', participating_in_scheme: false, created_at: Time.now, updated_at: Time.now },
  { brand: 'Ecotalk', host_network: 'EE', participating_in_scheme: false, created_at: Time.now, updated_at: Time.now },
  { brand: 'ETS Mobile', host_network: 'EE', participating_in_scheme: false, created_at: Time.now, updated_at: Time.now },
  { brand: 'FreedomPop', host_network: 'Three', participating_in_scheme: false, created_at: Time.now, updated_at: Time.now },
  { brand: 'Fonome Mobile', host_network: 'O2', participating_in_scheme: false, created_at: Time.now, updated_at: Time.now },
  { brand: 'Gamma Telecom', host_network: 'Three', participating_in_scheme: false, created_at: Time.now, updated_at: Time.now },
  { brand: 'Gemini Mobile', host_network: 'EE', participating_in_scheme: false, created_at: Time.now, updated_at: Time.now },
  { brand: 'giffgaff', host_network: 'O2', participating_in_scheme: false, created_at: Time.now, updated_at: Time.now },
  { brand: 'Global', host_network: 'EE', participating_in_scheme: false, created_at: Time.now, updated_at: Time.now },
  { brand: 'Globalgig', host_network: 'Three', participating_in_scheme: false, created_at: Time.now, updated_at: Time.now },
  { brand: 'HP Mobile Connect', host_network: 'EE', participating_in_scheme: false, created_at: Time.now, updated_at: Time.now },
  { brand: 'i3 Mobile', host_network: 'Three', participating_in_scheme: false, created_at: Time.now, updated_at: Time.now },
  { brand: 'iD Mobile', host_network: 'Three', participating_in_scheme: false, created_at: Time.now, updated_at: Time.now },
  { brand: 'JOi Telecom', host_network: 'Three', participating_in_scheme: false, created_at: Time.now, updated_at: Time.now },
  { brand: 'Jump', host_network: 'O2, Vodafone, EE, Three', participating_in_scheme: false, created_at: Time.now, updated_at: Time.now },
  { brand: 'Just Utilities', host_network: 'EE', participating_in_scheme: false, created_at: Time.now, updated_at: Time.now },
  { brand: 'KC Mobile', host_network: 'O2', participating_in_scheme: false, created_at: Time.now, updated_at: Time.now },
  { brand: 'Lebara Mobile', host_network: 'Vodafone', participating_in_scheme: false, created_at: Time.now, updated_at: Time.now },
  { brand: 'Lycamobile', host_network: 'O2', participating_in_scheme: false, created_at: Time.now, updated_at: Time.now },
  { brand: 'Meem Mobile', host_network: 'EE', participating_in_scheme: false, created_at: Time.now, updated_at: Time.now },
  { brand: 'NordTelekom', host_network: 'EE', participating_in_scheme: false, created_at: Time.now, updated_at: Time.now },
  { brand: 'Now PAYG', host_network: 'EE', participating_in_scheme: false, created_at: Time.now, updated_at: Time.now },
  { brand: 'Pebble Mobile Network', host_network: 'O2, Vodafone, EE, Three', participating_in_scheme: false, created_at: Time.now, updated_at: Time.now },
  { brand: 'Plusnet Mobile', host_network: 'EE', participating_in_scheme: false, created_at: Time.now, updated_at: Time.now },
  { brand: 'Rok Mobile', host_network: 'Three', participating_in_scheme: false, created_at: Time.now, updated_at: Time.now },
  { brand: 'RWG Mobile', host_network: 'Three', participating_in_scheme: false, created_at: Time.now, updated_at: Time.now },
  { brand: 'Sky Mobile', host_network: 'O2', participating_in_scheme: true, created_at: Time.now, updated_at: Time.now },
  { brand: 'SMARTY', host_network: 'Three', participating_in_scheme: false, created_at: Time.now, updated_at: Time.now },
  { brand: 'Superdrug Mobile', host_network: 'Three', participating_in_scheme: false, created_at: Time.now, updated_at: Time.now },
  { brand: 'Talk Home Mobile', host_network: 'EE', participating_in_scheme: false, created_at: Time.now, updated_at: Time.now },
  { brand: 'Talkmobile', host_network: 'Vodafone', participating_in_scheme: false, created_at: Time.now, updated_at: Time.now },
  { brand: 'TalkTalk Mobile', host_network: 'O2', participating_in_scheme: false, created_at: Time.now, updated_at: Time.now },
  { brand: 'TalkXtra Mobile', host_network: 'Vodafone', participating_in_scheme: false, created_at: Time.now, updated_at: Time.now },
  { brand: 'Telecom Plus', host_network: 'EE', participating_in_scheme: false, created_at: Time.now, updated_at: Time.now },
  { brand: 'Telfoni', host_network: 'Three', participating_in_scheme: false, created_at: Time.now, updated_at: Time.now },
  { brand: 'Tesco Mobile', host_network: 'O2', participating_in_scheme: true, created_at: Time.now, updated_at: Time.now },
  { brand: 'The Phone Co-op', host_network: 'EE', participating_in_scheme: false, created_at: Time.now, updated_at: Time.now },
  { brand: 'Torica Mobile', host_network: 'O2', participating_in_scheme: false, created_at: Time.now, updated_at: Time.now },
  { brand: 'Toggle Mobile', host_network: 'O2', participating_in_scheme: false, created_at: Time.now, updated_at: Time.now },
  { brand: 'Truphone', host_network: 'O2', participating_in_scheme: false, created_at: Time.now, updated_at: Time.now },
  { brand: 'Utilita', host_network: 'EE', participating_in_scheme: false, created_at: Time.now, updated_at: Time.now },
  { brand: 'Vectone Mobile', host_network: 'EE', participating_in_scheme: false, created_at: Time.now, updated_at: Time.now },
  { brand: 'Virgin Mobile', host_network: 'EE', participating_in_scheme: true, created_at: Time.now, updated_at: Time.now },
  { brand: 'Vivio', host_network: 'Vodafone', participating_in_scheme: false, created_at: Time.now, updated_at: Time.now },
  { brand: 'VOXI', host_network: 'Vodafone', participating_in_scheme: false, created_at: Time.now, updated_at: Time.now },
  { brand: 'White Mobile', host_network: 'EE', participating_in_scheme: false, created_at: Time.now, updated_at: Time.now },
  { brand: 'XLN Telecom', host_network: 'Three', participating_in_scheme: false, created_at: Time.now, updated_at: Time.now },
  { brand: 'Zevvle', host_network: 'EE', participating_in_scheme: false, created_at: Time.now, updated_at: Time.now },
])
