service_name_suffix: (local)
computacenter:
  outgoing_api:
    # Computacenter's dev endpoint
    # Uncomment this with reference to the UAT env to automatically send allocation cap updates to Computacenter
    # (assuming you also have valid settings for username: and password:
    # under the same scope)
    # endpoint:
