---
applications:
- name: get-help-with-tech-dev
  processes:
  - type: web
    disk_quota: 2G
    health-check-http-endpoint: /healthcheck.json
    health-check-type: http
    health-check-invocation-timeout: 60
    instances: 1
    timeout: 180
  - type: sidekiq
    disk_quota: 2G
    health-check-type: process
    instances: 1
    command: bundle exec sidekiq -C config/sidekiq.yml
  services:
    - get-help-with-tech-dev-db
    - get-help-with-tech-dev-redis
    - get-help-with-tech-dev-aws-s3-bucket
  env:
    DOCKER_IMAGE_ID: ((docker_image_id))
    ENV: $HOME/.profile
    RAILS_LOG_TO_STDOUT: true
    GHWT__SERVICE_NAME_SUFFIX: (dev)
    SERVICE_ENV: development
