---
applications:
- name: get-help-with-tech-prod
  disk_quota: 2G
  health-check-http-endpoint: /healthcheck.json
  health-check-type: http
  health-check-invocation-timeout: 10
  instances: 2
  services:
    - get-help-with-tech-prod-db
