---
applications:
- name: get-help-with-tech-prod
  processes:
  - type: web
    disk_quota: 2G
    health-check-http-endpoint: /healthcheck.json
    health-check-type: http
    health-check-invocation-timeout: 180
    instances: 4
  - type: sidekiq
    disk_quota: 2G
    health-check-type: process
    instances: 2
    command: bundle exec sidekiq -C config/sidekiq.yml
  services:
    - get-help-with-tech-prod-db
    - get-help-with-tech-prod-redis
    - get-help-with-tech-prod-aws-s3-bucket
  env:
    DOCKER_IMAGE_ID: ((docker_image_id))
    ENV: $HOME/.profile
    RAILS_LOG_TO_STDOUT: true
    SERVICE_ENV: production
