---
name: Build & push container

on:
  # Temp hack - run this whenever we push to this branch
  # Remove this trigger when the job is tested OK
  push:
    branches:
      - add-build-and-push-on-merge-workflow
  pull_request:
    types: [closed]
    branches:
      - master

jobs:
  build-container:
    runs-on: ubuntu-latest
# Only run this when the PR has been merged -
# put this back in when we've tested the job
# if: github.event.pull_request.merged

    steps:
      - name: checkout
        # Put this back in when PR merged
        # if: github.event.pull_request.merged
        uses: actions/checkout@v2

      - name: Declare some variables
        id: vars
        shell: bash
        run: |
          echo "##[set-output name=branch;]$(git rev-parse --abbrev-ref HEAD)"
          echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"

      - name: Build and push Docker image
        run: |
          echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
          make dev build push

      - name: Install CloudFoundry CLI
        shell: bash
        run: |
          # Install Cloud Foundry CLI
          # ...or Linux 64-bit binary
          # curl -L "https://packages.cloudfoundry.org/stable?release=linux64-binary&version=6.47.2&source=github" | tar -zx
          # ...move it to /usr/local/bin or a location you know is in your $PATH
          # mv cf ~
          wget -q -O - https://packages.cloudfoundry.org/debian/cli.cloudfoundry.org.key | sudo apt-key add -
          echo "deb https://packages.cloudfoundry.org/debian stable main" | sudo tee /etc/apt/sources.list.d/cloudfoundry-cli.list
          sudo apt-get update
          sudo apt-get install cf-cli
          echo "$(cf --version)"
      - name: Deploy to Gov.uk PaaS
        id: deploy-to-paas
        shell: bash
        run: |
          cf api https://api.london.cloud.service.gov.uk
          cf auth "${{ secrets.CF_USER }}" "${{ secrets.CF_PASSWORD }}"
          make dev deploy
