---
name: Build & push container

on:
  # Temp hack - run this whenever we push to this branch
  # Remove this trigger when the job is tested OK
  push:
    branches:
      - add-build-and-push-on-merge-workflow
  pull_request:
    types: [closed]
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
# Only run this when the PR has been merged -
# put this back in when we've tested the job
# if: github.event.pull_request.merged

    steps:
      - name: checkout
        # Put this back in when PR merged
        # if: github.event.pull_request.merged
        uses: actions/checkout@v2
      - name: Build and push Docker image
        uses: docker/build-push-action@v1
        with:
          build_args: GIT_COMMIT_SHA=$(git rev-parse --short "$GITHUB_SHA"),GIT_BRANCH=$(git rev-parse --abbrev-ref HEAD)
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: dfedigital/get-help-with-tech-dev
          tags: latest
