---
name: Build, push and deploy container

on:
  push:
    branches:
      - 215-add-docker-image-id-to-the-healthcheck-endpoint
  pull_request:
    types: [closed]
    branches:
      - main

jobs:
  build-and-push-container:
    runs-on: ubuntu-latest
    # Only run this when the PR has been merged -(i.e. not just closed)
    # if: github.event.pull_request.merged
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: Declare some variables
        id: vars
        shell: bash
        run: |
          echo "##[set-output name=branch;]$(git rev-parse --abbrev-ref HEAD)"
          echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"

      # We can't use the `make build push` task for this,
      # due to limitations in the way docker login works (or not) in non-TTY
      # Github actions. Helpfully, there's an off-the-shelf 'official' docker
      # action that does it for us
      - name: Build and push Docker image
        uses: docker/build-push-action@v1
        with:
          build_args: GIT_COMMIT_SHA=${{ steps.vars.outputs.sha_short }},GIT_BRANCH=${{ steps.vars.outputs.branch }}
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: dfedigital/get-help-with-tech-dev
          tags: latest


  deploy-to-paas:
    runs-on: ubuntu-latest
    needs: build-and-push-container
    # Only run this when the PR has been merged -(i.e. not just closed)
    # if: github.event.pull_request.merged
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: Install CloudFoundry CLI
        shell: bash
        run: |
          # Install Cloud Foundry CLI
          # ...or Linux 64-bit binary
          # curl -L "https://packages.cloudfoundry.org/stable?release=linux64-binary&version=6.47.2&source=github" | tar -zx
          # ...move it to /usr/local/bin or a location you know is in your $PATH
          # mv cf ~
          wget -q -O - https://packages.cloudfoundry.org/debian/cli.cloudfoundry.org.key | sudo apt-key add -
          echo "deb https://packages.cloudfoundry.org/debian stable main" | sudo tee /etc/apt/sources.list.d/cloudfoundry-cli.list
          sudo apt-get update
          sudo apt-get install cf-cli
          echo "$(cf --version)"

      - name: Get new docker image id
        id: get_docker_image_id
        shell: bash
        run: |
          echo "::set-output name=docker_image_id::$(docker pull dfedigital/get-help-with-tech-dev && docker image -q dfedigital/get-help-with-tech-dev)"

      - name: Deploy to Gov.uk PaaS
        id: deploy-to-paas
        shell: bash
        run: |
          cf api https://api.london.cloud.service.gov.uk
          cf auth "${{ secrets.CF_USER }}" "${{ secrets.CF_PASSWORD }}"
          DOCKER_IMAGE_ID=${{ steps.get_docker_image_id.outputs.docker_image_id }} make dev deploy
